### ISSUE TITLE
Terraform  is destroying and re-applying the vpc endpoint on each apply

### ISSUE THREAD

**Issue by egor-krv** [ClickHouse/terraform-provider-clickhouse#99] opened 2024-08-02 00:27 UTC
After the initial creation of the Private link config on each apply our Terraform  is destroying and re-applying the vpc endpoint every time  I run terraform apply.

**Comment by egor-krv** [comment] 2024-08-02 00:28
I was able to create all resources again and run plan. I can see that endpoints getting recreated when I ran plan. At a first glance I think that is how AWS provider plugin works but it might be for some reason the state does not get stored. I will investigate further and see if I can fix this.

**Comment by whites11** [comment] 2024-08-06 14:06
@egor-krv it seems to me this is a duplicate of https://github.com/ClickHouse/terraform-provider-clickhouse/issues/71 right?

**Comment by whites11** [comment] 2024-08-07 09:14
closing as duplicate

**Closed by whites11** 2024-08-07 09:14 UTC
